Bookstore: initialize project with components
sadaf-Daneshgar/bookstore pull request #1
Opened 2023-09-18 11:09 UTC by sadaf-Daneshgar

**New Features**

- ✅
- ✅
- ✅

2023-09-18 11:44 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @sadaf-Daneshgar  :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-18 11:44 UTC, Cabraham1 commented on src/components/Addbook.js
> +export default AddBook;
Great progress on your project so far! 👍🏿 However, in line with the project requirements, you are tasked with developing a book component, which includes a booklist component. This booklist component should receive book data as a prop and display the title and author of each book. Additionally, it should feature a button for removing books.

Please note that the button's functionality for removing books is currently a placeholder and is not yet operational.

<NewBookForm>
This component is responsible for rendering a form containing input fields for both the book's title and author. It also includes a submit button.

Similar to the previous button, the submit button's functionality for adding books is also a placeholder and is not yet functional.

2023-09-19 06:42 UTC, Ibizugbe requested changes
Hi @sadaf-Daneshgar 👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/sadaf-Daneshgar/bookstore/assets/64643995/7d3fdf67-e102-494f-bc46-bc98b66a3bf0)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] Add and remove functionality works well👍🏼.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-19 06:42 UTC, Ibizugbe commented on src/components/Addbook.js
> +              </span>
Just as the previous reviewer requested, kindly break the `addBook` component into separate components and ensure they are placed in separate files.

for instance, this `AddBook` component can contain the form for adding new books and be responsible for adding new books😉.

then you can create another component `Book` which should be in a separate file `Book.js`. this should take the book data as a prop and render the title and author of a book and has a button for removing books😉.
Lastly, another component called the `bookList` in a `bookList.js` file. this should be responsible for rendering all the books in the array😉.

I understand you have implemented these features in this class, but breaking your project into smaller components is important for component reusability and separation of concerns😉. This makes your codebase readable and maintainable👍🏼.

2023-09-21 16:41 UTC, usorfaitheloho approved these changes
Hi @sadaf-Daneshgar  , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 11:17 UTC, merged